
deployUrl=file:///Users/cer/.m2/testdeploy

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

springBootVersion=3.4.7

eventuatePlatformVersion=2026.1.BUILD-SNAPSHOT
eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT
dockerComposePluginVersion=0.17.7
eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.20.0.BUILD-SNAPSHOT
eventuateExamplesBaseImageVersion=BUILD-17
springDocOpenApiUiVersion=2.8.6

junitVersion=5.12.2
junitPlatformLauncherVersion=1.12.2
assertjVersion=3.26.3

version=0.1.0-SNAPSHOT
