apply plugin: FtgoServicePlugin

dependencies {
    implementation project(":common")
    implementation project(":customer-service-api-events")
    implementation project(":order-service-api-events")

    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"

    implementation project(":order-history-service-common")

    implementation "io.eventuate.tram.core:eventuate-tram-spring-events"
    implementation "io.eventuate.tram.core:eventuate-tram-consumer-redis"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
