apiVersion: v1
kind: Service
metadata:
  name: order-history-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    svc: order-history-service
  ports:
  - port: 8083
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    matchLabels:
      svc: order-history-service
  template:
    metadata:
      labels:
        svc: order-history-service
    spec:
      containers:
      - name: order-history-service
        image: eventuateexamples/eventuate-tram-examples-customers-and-orders-order-history-service:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://mongodb/customers_and_orders
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: zookeeper:8121
          - name: SPRING_SLEUTH_ENABLED
            value: "true"
          - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
            value: "1"
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin:9411
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 14
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 14
---
