apiVersion: v1
kind: Service
metadata:
  name: order-history-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    svc: order-history-service
  ports:
  - port: 8083
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-history-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    matchLabels:
      svc: order-history-service
  template:
    metadata:
      labels:
        svc: order-history-service
    spec:
      containers:
      - name: order-history-service
        image: eventuateexamples/eventuate-tram-examples-customers-and-orders-redis-order-history-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: EVENTUATE_REDIS_SERVERS
            value: redis:6379
          - name: EVENTUATE_REDIS_PARTITIONS
            value: "2"
          - name: SPRING_PROFILES_ACTIVE
            value: Redis
          - name: SPRING_SLEUTH_ENABLED
            value: "true"
          - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
            value: "1"
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin:9411/
          - name: JAVA_OPTS
            value: -Xmx128m
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 14
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 14
---
