apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  ports:
  - port: 8081
    targetPort: 8080
  selector:
    svc: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    svc: order-service
spec:
  selector:
    matchLabels:
      svc: order-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: order-service
    spec:
      containers:
      - name: order-service
        image: eventuateexamples/eventuate-tram-examples-customers-and-orders-order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            value: mysqluser
          - name: SPRING_DATASOURCE_PASSWORD
            value: mysqlpw
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: zookeeper:2181
          - name: CDC_SERVICE_URL
            value: http://cdc-service:8080
          - name: SPRING_SLEUTH_ENABLED
            value: "true"
          - name: SPRING_SLEUTH_SAMPLER_PROBABILITY
            value: "1"
          - name: SPRING_ZIPKIN_BASE_URL
            value: http://zipkin:9411/
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 14
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 14
---
