apiVersion: 1

datasources:

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://localhost:9411
    editable: true
    uid: zipkin9411
    
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    editable: true
    isDefault: true
    jsonData:
      derivedFields:
        - datasourceUid: zipkin9411
          matcherRegex: "\\[.*,(\\w+),.*,.*\\]"
          name: TraceID
          url: "$${__value.raw}"

