---
    apiVersion: eksctl.io/v1alpha5
    kind: ClusterConfig
    
    metadata:
      name: customers-and-orders-redis
      region: ap-southeast-1
    
    managedNodeGroups:
    - name: nodegroup
      instanceType: t2.micro
      desiredCapacity: 7
      iam:
        withAddonPolicies:
          albIngress: true
    vpc:
      nat:
        gateway: Disable
