apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    role: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  selector:
    matchLabels:
      role: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        role: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: eventuateio/eventuate-mysql
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: mysqluser
            - name: MYSQL_PASSWORD
              value: mysqlpw
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
      namespace: eventuate-tram-examples-customers-and-orders
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 256Mi
---