apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    svc: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    svc: redis
spec:
  selector:
    matchLabels:
      svc: redis
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: httpport
---