apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: eventuate-tram-examples-customers-and-orders
spec:
  ports:
  - port: 9411
    targetPort: 9411
  selector:
    svc: zipkin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: eventuate-tram-examples-customers-and-orders
  labels:
    svc: zipkin
spec:
  selector:
    matchLabels:
      svc: zipkin
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.21
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9411
          name: httpport
        env:
          - name: JAVA_OPTS
            value: "-Xmx64m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 60
          periodSeconds: 20
---