dependencies {
    testImplementation project(":common")
    testImplementation project(":order-service-api-events")

    testImplementation project(":order-history-service-common")
    testImplementation project(":customer-service-api-web")
    testImplementation project(":order-service-api-web")

    testImplementation "org.springframework.boot:spring-boot-starter-web"
    testImplementation "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
}
